### ISSUE TITLE
Vegemite colour?!

### ISSUE THREAD

**Issue by thomasfoster96** [dp-lewis/postcss-australian-stylesheets#6]
Not sure where you've been getting your Vegemite, but it looks much too brown for me - in fact, I'd say it looks more like vegemite on buttered toast.

**Comment by dp-lewis** [comment]
I've been assured that the contributor for the Vegemite colour went to great lengths to establish it. But if you're keen to update feel free to put a PR together :)

**Comment by thomasfoster96** [comment]
Ah right well I'll leave it as is if there has been extensive testing.
